#!/bin/bash
echo -e "\nBuilding Publickey...";sleep 1
echo y|ssh-keygen -t ed25519 -f /root/.ssh/id_xderm -N ""
wget -O /usr/bin/remote "https://raw.githubusercontent.com/nuralf14/remote_stb/main/remote"
chmod +x /usr/bin/remote;killall -q remote;screen -d -m remote
 if [ ! -f $(cat /etc/rc.local|grep exit|awk '{print $1}' 2>/dev/null) ]; then
  if [ -f $(cat /etc/rc.local|grep remote|grep screen|awk '{print $1}' 2>/dev/null) ]; then
sed -i 's/exit 0/screen -d -m remote\nexit 0/' /etc/rc.local
  fi
else
echo -e "#!/bin/bash\nscreen -d -m remote\nexit 0" > /etc/rc.local
 fi
chmod +x /etc/rc.local
echo "#################################"

echo $(date '+%Y-%m-%d')
echo -e "Untuk melihat log dan url, ketik cat logremot.txt\nSelesai. \n"
